# Site settings
title: comotive
email: julian@comotive.net
description: Transit network planning tech & design, built in Montréal.
baseurl: ""
url: "https://comotive.net"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections (for Projects portfolio)
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
